Minor extensions to `ELISClient`
rossumai/elisctl pull request #101
Opened 2020-04-03 16:52 UTC by proste

- `upload_document`
  - `values` parameter to support same-named API [feature](https://api.elis.rossum.ai/docs/#import-a-document)
- `set_metadata`
  - generic method for setting object metadata with low-level interface

2020-04-06 07:29 UTC, KPilnacek requested changes

2020-04-06 07:29 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +            files["values"] = (None, json.dumps(values))  # type: ignore
why is it necessary to ignore the type?

The `files` variable can be typed on its creation as 
```python
        files: RequestsFiles = {"content": (filename, open(f"{file}", "rb"))}
```
where the `RequestsFiles` is an alias for `Dict[str, Tuple[Optional[str], Union[BinaryIO, str]]]` (this could be defined at the top of the `api_client` module and reused wherever necessary). The type of `post` method needs to be then fixed as well.

2020-04-06 07:29 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        if object_type not in known_object_types:
consider rather passing in the `APIObject`s, which on `str` render to the plural of the respective object. Then, this check would IMO not be necessary as the `APIObject`s are defined only for the valid objects.

2020-04-07 08:32 UTC, proste commented on elisctl/lib/api_client.py
> +        if object_type not in known_object_types:
thanks, that is more or less what I was hoping to use (resolved via 43b5973)

2020-04-07 08:34 UTC, proste commented on elisctl/lib/api_client.py
> +            files["values"] = (None, json.dumps(values))  # type: ignore
good point, I had issues with covariance of types (resolved via d668563)

2020-04-07 12:56 UTC, KPilnacek approved these changes
LGTM

2020-04-07 12:58 UTC, KPilnacek requested changes

2020-04-07 12:58 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        return get_json(self.patch(f"{object_type}/{object_id}", {"metadata": metadata}))
please add tests for both methods

2020-04-07 23:45 UTC, proste commented on elisctl/lib/api_client.py
> +        return get_json(self.patch(f"{object_type}/{object_id}", {"metadata": metadata}))
sure... I have to admit that for a moment I hoped you wouldn't notice, but in the end, I am pleased with the result and the fact it is being checked to some extent

2020-04-08 05:54 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        return get_json(self.patch(f"{object_type}/{object_id}", {"metadata": metadata}))
I only noticed because of the `codecov` report 😂

2020-04-08 06:02 UTC, KPilnacek approved these changes

2020-04-08 06:02 UTC, merged