Enhance APIClient for serverless functions
rossumai/elisctl pull request #116
Opened 2020-08-18 13:10 UTC by tbots

2020-08-26 11:56 UTC, evelyn9191 commented
Travis CI checks failed, please fix the linting.

2020-08-26 12:09 UTC, evelyn9191 requested changes

2020-08-26 12:09 UTC, evelyn9191 commented on elisctl/lib/api_client.py
>          return get_json(self.post("webhooks", data))
When we are already updating it, consider changing the `/webhooks` to `/hooks`. It is OK to do so in a separate PR or here.

2020-10-19 12:57 UTC, tbots commented
All changes in this PR have been implemented in the https://github.com/rossumai/rossum/pull/7 and https://github.com/rossumai/rossum/pull/6

2020-10-19 12:57 UTC, closed without merging