Segregate webhook and function options
rossumai/elisctl pull request #122
Opened 2020-09-17 10:22 UTC by tbots

2020-09-23 09:20 UTC, evelyn9191 requested changes

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/option.py
>      "--config_insecure_ssl",
Consider keeping the syntax consistent. In other options, only dashes, not underscores are used.

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/option.py
> +    help="String-serialized source code to be executed.",
`help="Path to the file with the string-serialized source code to be executed.",`

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/option.py
> +    help="Runtime used to execute code. Allowed values: nodejs12.x.",
If there is only one allowed value, then the user shouldn't be prompted to add this option at all. Consider removing it and fill it for the user within the function create_command().

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/workspace.py
> +        # use create_workspace method
This is probably forgotten comment

2020-09-23 09:20 UTC, evelyn9191 commented on setup.py
> +        "click-option-group==0.5.1",
This library is not used anymore I believe

2020-09-23 09:20 UTC, evelyn9191 commented on tests/test_hook.py
> +CONFIG_CODE = "tests/data/snippet_code.js"
Please use something like
```
ROOT_DIR = Path(__file__).absolute().parents[1]
CONFIG_CODE = ROOT_DIR / "tests" / "data" / "snippet_code.js"
```
Because this path is not accessible for all OS. Refer to https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f for example

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +@option.config_runtime
Why are `**kwargs` not used instead? It would make it easier to work with the config related data later in the function.

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +        if hook_type == "webhook":
Please make the parts as abstract (=as reusable) as possible. This `if-elif` condition should be as one part, ideally.

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +                f"{response['id']}, {response['name']}, {response['queues']}, {response['events']}, {response['config']['url']}, {response['config']['secret']}"
For the config data, you could do something like
`{[value for value in response['config'].items()]}` to manage different config keys for function and webhooks (see the comment above).

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/option.py
> -    default=False,
Why is default removed?

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +@option.hook_type
I think we should list all the hooks when the customer asks for listing all hooks, not to differentiate them by the type.

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +@option.hook_type
Then, based on that, please refactor the list_command() body so that it is more abstract and does not differentiate between the hook types.

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/hook.py
> +        if hook_type == "webhook":
As mentioned in the previous comments, please make it more abstract to cover both webhook and function, without having to split it to a large if-else condition (this is also the reason why the checks failed).

2020-09-23 09:20 UTC, evelyn9191 commented on elisctl/lib/api_client.py
> +        query = {"type": f"{hook_type}"}
I don't think this is necessary, actually. It should list all hooks.

2020-09-23 09:20 UTC, evelyn9191 commented on tests/conftest.py
> +    assert request.json() == uploaded_json
Why is this changed?

2020-09-23 09:20 UTC, evelyn9191 commented on tests/test_hook.py
> +    def test_non_admin_does_not_see_auth_token__if_type_webhook(self, requests_mock, cli_runner):
When you list all webhooks, you list all webhooks disregarding of their type. Please make this and `test_non_admin_does_not_see_auth_token_if_type_function` into one test and adjust also other tests for listing as needed after the `list_command()` refactor.

2020-09-23 09:20 UTC, evelyn9191 commented on tests/test_hook.py
> +    def test_success_if_type_webhook(self, requests_mock, cli_runner):
Please make the functions as reusable as possible. A lot of the variables used here are repetitive. Consider creating one functions that will be responsible for the core of the json request in the `requests_mock.patch` and the list passed to the `change_command` and then using `@pytest.mark.parametrize` you can parametrize the tests to send only needed values to the core json request. You can refer to some of our internal connectors to see how we usually do it when using various annotation trees over and over. The point is not to repeat the same code.

2020-09-24 12:39 UTC, KPilnacek commented on tests/conftest.py
> +    assert request.json() == uploaded_json
We started to use this pattern on BE in order to find faster the reason, why we are getting a `NoMockAddress`

2020-10-06 13:26 UTC, evelyn9191 requested changes

2020-10-06 13:26 UTC, evelyn9191 commented on tests/test_hook.py
> +            f"Error: Missing option {expected}\n"
I'd probably go with something like 
`assert f"Error: Missing option {expected}\n" in result.output`
for these verbose cases, but it's not a big deal, you can keep it as it is

2020-10-06 13:26 UTC, evelyn9191 commented on elisctl/hook.py
> +def cleanup_config(config):
Super unimportant nitpick - let's use the typing hints to help us along the way.
`def cleanup_config(config: Dict) -> Dict:`

2020-10-15 09:50 UTC, evelyn9191 requested changes
Please react to the comments

2020-10-15 10:01 UTC, tbots commented on elisctl/option.py
> +    help="Runtime used to execute code. Allowed values: nodejs12.x.",
@evelyn9191 according to supported runtimes (https://api.elis.rossum.ai/docs/#validating-payloads-from-rossum) a customer can use another runtime, as I understood there can be different runtime options, it is true? I can remove this part "Allowed values: nodejs12.x." from help text

2020-10-15 10:03 UTC, tbots commented on elisctl/workspace.py
> +        # use create_workspace method
@evelyn9191  you are right, thanks, I will remove it in the next commit

2020-10-15 10:41 UTC, evelyn9191 requested changes

2020-10-15 10:41 UTC, evelyn9191 commented on elisctl/option.py
> +    help="Runtime used to execute code. Allowed values: nodejs12.x.",
But the documentation says:
```Currently Rossum supports NodeJS 12 runtime (nodejs12.x) to execute JavaScript functions. If you would like to use another runtime, please let us know at product@rossum.ai.

Please be aware that we may eventually deprecate and remove runtimes in the future (deprecation will be announced at least 6 months before the deprecation date).
```

From this it sounds to me that we are planning to deprecate them rather than keep them. It would be the best to find out to ask the Product team what are the plans and what is the most probable scenario.

2020-10-15 10:43 UTC, tbots commented on elisctl/option.py
> +    help="Runtime used to execute code. Allowed values: nodejs12.x.",
@evelyn9191 thank you, I will ask them

2020-10-16 11:00 UTC, tbots commented
All changes in this PR have been implemented in the https://github.com/rossumai/rossum/pull/6

2020-10-16 11:00 UTC, closed without merging