Add document command
rossumai/elisctl pull request #56
Opened 2019-05-02 20:30 UTC by evelyn9191

2019-05-04 14:02 UTC, KPilnacek commented
This is an installable package, which uses `setup.py`, where all the first level dependencies are defined (dependencies are not pinned down to exact version).

Moreover, `mypy` checks are failing.

2019-05-10 07:24 UTC, KPilnacek requested changes
Seems to be working. That's great! But I'd polish it.

2019-05-10 07:24 UTC, KPilnacek commented on .pre-commit-config.yaml
> +    rev: v2.2.1
please put these into a different commit

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/csv.py
> +        df.to_csv(buffer, sep=";", index=False, line_terminator="\n")
please explain why this is necessary, maybe put a comment

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    json_response = upload_documents(id_, elis, files)
I'd rather put the `upload_documents` function outside the `get_ids` as
- `get...` functions should not do any fancy stuff -- only extract the IDs from a JSON
-  get_ids does not express that it actually uploads the documents to ELIS

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +def get_annotation(annotation: str, max_retries=120, sleep_secs=5):
please make this function more general (mainly allow passing in the`is_done ` function) and stick it to the `ELISClient` class for other possible usage

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +        print(".", end="")
use `click.echo` instead of plain `print` (IIRC it takes care about some encoding issues in windows)

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +def _content_type(document_path: str) -> Optional[str]:
use rather something like `magic` or `mimetypes`. Actually, I don't think it's not necessary to send content-type to the ELIS API.

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +def upload_documents(id_: int, elis: ELISClient, files: Optional[List[Tuple[str]]]) -> dict:
please stick  this function to the ELISClient class for other possible usage

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +@click.argument("id_", metavar="ID", type=str)
what ID is this?

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    [get_annotation(one_annotation_id) for one_annotation_id in get_annotation_ids]
I don't think, this is a good usage for a comprehensions. They should be used for creating new lists not for iterating. More on this topic: https://treyhunner.com/2019/03/abusing-and-overusing-list-comprehensions-in-python/

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +        export_data = elis.get(f"queues/{id_}/export?id={ids}?format={format_}")
Please create a specific method in `ELISClient` for exporting rather than using lower level API.

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    upload_response = elis.post(path=f"queues/{id_}/upload", files=upload_files)
although it is possible to upload multiple documents at once, I'd rather upload them one by one as the max upload size might be hit (at the moment it is 50 MB) and status 413 might be returned.

2019-05-10 07:24 UTC, KPilnacek commented on pyproject.toml
> +target-version = ["py37"]
please put this to a different commit

2019-05-10 07:24 UTC, KPilnacek commented on tests/test_extract_data.py
> +INV_PDF = "tests/data/invoice.pdf"
It's not necessary to have actual files for the tests.

2019-05-10 07:24 UTC, KPilnacek commented on tests/test_extract_data.py
> +            json={"url": f"{ANNOTATION_TO_REVIEW}", "status": "to_review"},
please test also polling. Multiple responses can be included using a list in here (for details see https://requests-mock.readthedocs.io/en/latest/response.html#response-lists)

2019-05-10 07:24 UTC, KPilnacek commented on tests/test_extract_data.py
> +OUTPUT_JSON = {
it's not necessary to have that much information as it is not checked in the test nor necessary in the commands themselves.

2019-05-10 07:24 UTC, KPilnacek commented on tests/test_extract_data.py
> +            request_headers={"Authorization": f"Token {TOKEN}"},
check also the uploaded request using `aditional_matcher` parameter

2019-05-10 07:24 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    return annotations_ids
what for are the IDs necessary?

On [L. 101](https://github.com/rossumai/elisctl/pull/56/files#diff-5bad71ea04836095f7595c393643c4dfR101) are the URLs recreated. It would be simpler to just use the URLs instead.

2019-05-13 09:05 UTC, evelyn9191 commented on elisctl/csv.py
> +        df.to_csv(buffer, sep=";", index=False, line_terminator="\n")
`line_terminator` is set to ensure universal newline support. When tests are run on Mac, they may be passing, but on Windows they are failing, because while Mac counts with `\r\n` code for a new line, Windows uses only `\n`. With the predefined line terminator, all three platforms should be handled.

2019-05-14 07:27 UTC, KPilnacek commented on elisctl/csv.py
> +        df.to_csv(buffer, sep=";", index=False, line_terminator="\n")
Fair enough, however, how will Windows handle the csv? Is it possible to open it?
If it is OK, then please add a comment in here. Otherwise, the tests need to be fixed -- not the code.

2019-05-26 06:37 UTC, evelyn9191 commented on elisctl/document/extract_data.py
> +    return annotations_ids
IDs are needed for filtering the correct annotations when exporting the data (as in `/queues/123/export?id=125,126`)

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +def cli() -> None:
unused

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +locale_option = click.option(
unused

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    return annotations_ids
Then, I'd place the parsing into `ELISClient.export_data` method as it is not necessary anywhere else

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +@click.argument("queue_id", metavar="ID", type=str)
From the help on CLI is not clear, what ID should be provided:
```shell
$ elisctl document extract -h
Usage: elisctl document extract [OPTIONS] ID FILE

  Extract data from the uploaded files.

Options:
  -O, --output-file FILENAME
  --indent INTEGER
  --ensure-ascii
  --format [json|csv|xml]
  -h, --help                  Show this message and exit.
```

Just a remark: help could be also written as a docstring (see `user.create_command`).

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    with ELISClient() as elis:
using `ELISClient` within a with block causes the elisctl to login at the start of the block and logout at the end. Try to avoid the login/logout for every status check.

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        return self.get(f"queues/{id_}/export?id={ids}?format={format_}")
There are two `?` in the URL. That, I guess, won't work really well (if at all). Consider rather using `query` parameter of the `get` method.

2019-06-03 13:19 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        files: List[Tuple] = None,
the `mypy` issues can be solved by having the same type of `files` as in `post` method

2019-06-03 13:19 UTC, KPilnacek commented on tests/test_extract_data.py
> +    def test_get_data(self, requests_mock, cli_runner):
please use `isolated_cli_runner` when you touch files. That ensures that all file-system changes are isolated and the environment is always the same.

2019-06-03 13:19 UTC, KPilnacek commented on tests/test_extract_data.py
> +INV_PDF = "./data/invoice.pdf"
creating absolute paths (devised from `__file__` variable) might help you out from the issues with tests.

2019-06-14 09:16 UTC, evelyn9191 commented on elisctl/document/extract_data.py
> +    return annotations_ids
The annotations IDs will be actually needed at more places after the refactor of the function in the next commits, so I will keep it for now

2019-06-21 12:22 UTC, KPilnacek requested changes

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        return annotation
consider rewriting this with a [guarding clause](https://refactoring.guru/replace-nested-conditional-with-guard-clauses):
```python
if id_ is None:
    raise click.ClickException("Annotation ID wasn't specified.")
return get_json(self.get(f"{ANNOTATIONS}/{id_}"))
```

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +@output_file
please use the namespaced version `@option.output_file`

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +    return annotation_id_number
this code will fail with `NameError` if `annotation_id is None`

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +        r"(?<=annotations/)\d*$", annotation_url, flags=re.MULTILINE | re.IGNORECASE
why are these flags (`flags=re.MULTILINE | re.IGNORECASE`) necessary?

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/document/extract_data.py
> +def get_id(json_response: Response) -> int:
the type of `json_response` should be `dict`

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +    def get_annotation_status(self, annotation: int):
I'd rather make this a private method as it is coupled with `poll_annotation_status` method. Moreover, I'd rather name it sth like `_get_annotation_polling` and I'd move it behind the `poll_annotation_status` method, where it is being used (in the spirit of [top down approach](https://dbader.org/blog/how-to-structure-python-programs)).

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +    ):
please add the return type (I guess it should be `dict`)

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +    def get_annotation_status(self, annotation: int):
and please add the return type

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +    def poll_annotation_status(
I think that `status` in the name is not necessary, as you can actually poll on anything from the annotation_object. As well as the `check_status` variable could be simply named as in the polling library `check_success` (it need not to check only status).

2019-06-21 12:22 UTC, KPilnacek commented on setup.py
> +        "requests",
`requests` are already specified in the list

2019-06-21 12:22 UTC, KPilnacek commented on setup.py
> +        "polling",
"jmespath" and "polling" need to be added to installer.cfg file in order to have a working windows build

2019-06-21 12:22 UTC, KPilnacek commented on setup.py
> +        "polling",
actually please use [`polling2`](https://github.com/ddmee/polling2) instead of `polling` as the latter is not active anymore

2019-06-21 12:22 UTC, KPilnacek commented on setup.py
> +        "polling",
The include section of installer.cfg should look:
```
[Include]
pypi_wheels = certifi==2019.6.16
    chardet==3.0.4
    Click==7.0
    click-shell==1.0
    idna==2.8
    jdcal==1.4.1
    jmespath==0.9.4
    numpy==1.16.4
    pandas==0.24.2
    polling2==0.4.3
    python-dateutil==2.8.0
    pytz==2019.1
    requests==2.22.0
    six==1.12.0
    urllib3==1.25.3
    xlrd==1.2.0
packages = tabulate
    jsondiff
    openpyxl
    et_xmlfile
```

2019-06-21 12:22 UTC, KPilnacek commented on tests/test_extract_data.py
> +                    "headers": {"Authorization": "Token %s" % TOKEN},
consider using some of the more modern string interpolations (like `.format` or f-strings).
This type of string interpolation is only necessary in `logging` module, where it allows for easier grouping of logged messages.

2019-06-21 12:22 UTC, KPilnacek commented on tests/test_extract_data.py
> +                    "json": {"results": [{"annotation": "%s" % ANNOTATION_FAILED}]},
no need to use string interpolation. `{"annotation": ANNOTATION_FAILED}` should suffice

2019-06-21 12:22 UTC, KPilnacek commented on tests/test_extract_data.py
> +        assert not result.exit_code, print_tb(result.exc_info[2])
I think we should also assert the result of this command (even though it will probably be the same as OUTPUT_JSON)

2019-06-21 12:22 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +        file_info = {"content": open(f"{file}", "rb")}
consider renaming `file_info` to `files`

2019-06-21 12:22 UTC, KPilnacek commented on tests/test_extract_data.py
> +            request_headers={"Authorization": f"Token {TOKEN}"},
consider using  parameter `complete_qs=True` in order to check that the querystring is exactly the one as in `EXPORT_ENDPOINT`

2019-06-21 12:22 UTC, KPilnacek commented on tests/test_extract_data.py
> +                },
I don't think that this part of list is ever used

2019-06-21 12:28 UTC, KPilnacek commented
I see the light at the end of the tunnel 🙂. The biggest issue now, are the missing dependencies in `installer.cfg` file. The rest, I hope, are just some minor things.

2019-06-21 13:59 UTC, evelyn9191 commented on elisctl/lib/api_client.py
> +        return annotation
Thanks for the tip!

2019-06-24 18:25 UTC, KPilnacek requested changes

2019-06-24 18:25 UTC, KPilnacek commented on tests/test_extract_data.py
> +                    "headers": {"Authorization": f"Token {TOKEN}"},
I think you want to check that sent header (i.e. `request_headers`) contain `"Authorization": f"Token {TOKEN}"`. The current setup won't check the header but will send this header back.

2019-06-24 18:25 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +            click.echo(".", nl=False)
consider using `click.echo(..., err=True)` (similarly to `elisctl.schema.xlsx`), in order to allow using `>` for the resulting json file. Without the `err=True` the resulting file would also include these logging strings.

2019-07-08 11:16 UTC, evelyn9191 commented on setup.py
> +        "polling",
Thank you

2019-07-08 11:36 UTC, evelyn9191 commented on tests/test_extract_data.py
> +                    "headers": {"Authorization": f"Token {TOKEN}"},
I wanted to monitor various polling responses in a specific order rather than headers check. With the list of various responses, `request_headers` is not available. So for this check, `json` and `status_code` are more relevant.

2019-07-09 07:05 UTC, KPilnacek approved these changes

2019-07-09 07:07 UTC, KPilnacek commented
Done :). Please only squash the fixup commits to 61ca67a796443450609514a74f454ddb17f83ed8.

2019-07-09 09:00 UTC, merged