Add connector command
rossumai/elisctl pull request #59
Opened 2019-05-10 15:15 UTC by evelyn9191

2019-05-14 09:24 UTC, KPilnacek requested changes
Seems to be working 👍, though, some refactors would be useful.

There are some contradictory comments, please choose the best ones :-)

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/options.py
> +def service_url_option(command: Optional[Callable] = None, **kwargs):
this kind of decorator is used when one needs to have an `option` with lots of defaults but some of them need to be sometimes adjusted.

However, the usage of this and the following option-decorators is not changed. Either go the simpler way as is the `queue_option` decorator, or use the decorator the way it should be used.

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/options.py
> +queue_option = click.option(
please reuse code as much as possible. This is a duplicate (except the ss in `queues-ids`) of `user.options.queue_option`.

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/options.py
> +def asynch_option(command: Optional[Callable] = None, **kwargs):
`asynch`, compared to `async`, is not a really common abbreviation of `asynchronous` (thousands of results on google: asynch 278, async 44300). I'd rather name this option `async` or `asynchronous`.

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +def cli() -> None:
unused

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +            queue_dict = get_json(elis.get(f"queues/{queue}"))
use rather `elis.get_queue(queue)` instead of `get_json(elis.get(f"queues/{queue}"))`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +        response = elis.post(
please extract this as a method `create_connector` of `ELISClient`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +    with APIClient() as api_client:
use rather `ELISClient`. The `get_json(api_client.get(f"queues/{queue}"))` could be simplified to `elis.get_queue(queue)`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +        elis.delete(to_delete={f"{id_}": f"{url}/connectors/{id_}"}, verbose=2, item="connector")
verbose is intended to be provided as a parameter of the command

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +        url = APIClient().url
`ELISClient` inherits from `APIClient`, thus, `url` is available also on `elis`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +@click.confirmation_option()
Please provide some help to the confirmation option (for inspiration see `queue.delete_command`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +    queues = {queue["url"]: queue.get("id", "") for queue in queues_list}
do this rather the way of `queue.list_command`, i.e. create a method `ELISClient.get_connectors` (similar to `ELISClient.get_workspaces`) and use it instead of the 3 lines above

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +ORGANIZATION_ID = "1"
unused

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +        assert not f"{CONNECTOR_ID}, {CONNECTOR_NAME}" == result.output
why `not`?

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +                        "asynchronous": ASYNCHRONOUS,
no need to mock things that are not used in the code (i.e. params, authorization_token, asynchronous)

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +        _, id_ = url.rsplit("/", 1)
unused

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +        json=_get_queue_json_callback,
consider rather using a lambda as the `_get_queue_json_callback` is very simple

2019-05-14 09:24 UTC, KPilnacek commented on tests/test_connector.py
> +def mock_queues_urls(requests_mock):
used only once, thus, it could be used directly, where it is necessary

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +def change_command(
cannot change name

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +            ", ".join(str(queues[q]) for q in connector["queues"]),
I'd also list params and asynch

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/__init__.py
> +@cli.command(name="list", help="List all connectors.")
consider also including connector in the list command of queue

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +@service_url_option(default=None, show_default=False)
consider making this field required

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +@auth_token_option(default=None, show_default=False)
consider generating the token if not provided

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +@asynch_option(default=None, show_default=False)
consider having `default=True`

2019-05-14 09:24 UTC, KPilnacek commented on elisctl/connector/create.py
> +from elisctl.connector import (
the problem with `mypy` will disappear when you'll import directly from `elisctl.connector.options`. The problem is probably with some circularity of imports

2019-06-02 11:34 UTC, evelyn9191 commented on tests/test_connector.py
> +                        "asynchronous": ASYNCHRONOUS,
Are used in the new version after the refactor, so I kept them there

2019-06-03 12:11 UTC, KPilnacek commented on elisctl/connector.py
> +@queue
please use namespaced versions of the options (i.e. `option.queue`), to include the information whether it is queue or argument

2019-06-03 12:11 UTC, KPilnacek commented on elisctl/connector.py
> +                queue_urls.append(queue_dict["url"])
consider using `get_queues` and filtering out the unwanted queues.

At the moment, when the queue is "unreachable" (for instance: does not exists) elisctl will fail with the following error:
`'Error: Invalid response [httpmock://api.elis.rossum.ai/v1/queues/1]: {"url": "httpmock://api.elis.rossum.ai/v1/queues/1"}'`. The proposed way would overcome this.

2019-06-03 12:11 UTC, KPilnacek commented on elisctl/connector.py
> +@click.argument("id_", metavar="ID", type=str)
there exists decorator `argument.id_`, consider using that one

2019-06-03 12:11 UTC, KPilnacek commented on elisctl/connector.py
> +@asynchronous_option(default=True, show_default=False)
the [comment](https://github.com/rossumai/elisctl/pull/59#discussion_r283661940) applies also to `params_option` and `asynchronous_option`

2019-06-13 06:55 UTC, KPilnacek commented on elisctl/connector.py
>  def create_command(
the tests are failing because there is missing decorator `@click.pass_context`

2019-06-13 11:15 UTC, KPilnacek commented on tests/test_connector.py
> +        json=_get_queue_json_callback,
```python
json=lambda r, c: {"url": r.url},
```

2019-06-13 12:59 UTC, KPilnacek approved these changes
LGTM

2019-06-13 13:00 UTC, merged