Enhancement/make queue parameter required for connector
rossumai/elisctl pull request #75
Opened 2019-07-21 16:16 UTC by evelyn9191

2019-07-24 07:53 UTC, KPilnacek requested changes

2019-07-24 07:53 UTC, KPilnacek commented on elisctl/connector.py
> +                raise click.ClickException("Queue ID(s) must be specified.")
consider rather using something like:
```python
        if queue_ids:
            queue_urls = [q['url'] for q in elis.get_queues() if int(q['id']) in queue_ids]
        else:
            queue_urls = [elis.get_queue()['url']]
```
in order to decrease the number of requests and simplify the code. The following for loop would be also replaced by this code.

2019-07-24 07:53 UTC, KPilnacek commented on elisctl/connector.py
> +def _is_empty(attr: Any):
Please explain `_is_empty` function. It returns `False` when `queue_ids == (1,2)`. That doesn't sound to me as correct result of function that should check if sth is empty.

2019-07-24 07:53 UTC, KPilnacek commented on elisctl/connector.py
> +            f"{response['id']}, {response['name']}, attached to the queue(s) {response['queues']}"
I'd rather keep the outputs of elisctl programmatically parsable (i.e. leave out "attached to the queue(s)").

2019-07-24 07:53 UTC, KPilnacek commented on elisctl/connector.py
> +    element="connector",
element="connector", not necessary as it is overwritten in help anyway

2019-07-24 07:53 UTC, KPilnacek commented on elisctl/option.py
> +def queue(command: Optional[Callable] = None, element: Optional[str] = "object", **kwargs):
consider renaming `element` to sth like `related_object`

2019-07-25 05:58 UTC, evelyn9191 commented on elisctl/connector.py
> +def _is_empty(attr: Any):
That sounds correct to me. If <code>queue_ids == (1,2)</code>, then the tuple is not empty and <code>_is_empty</code> should return <code>False</code>.<code>_is_empty</code> checks if the value equals <code>None</code> or (particularly in this case) <code>()</code> - in such case it returns <code>True</code>. It is a variation on <code>if len(x) == 0</code>.

2019-08-01 12:12 UTC, KPilnacek commented on elisctl/connector.py
> +def _is_empty(attr: Any):
Oh, sorry, my bad. It's correct.

However, I'd rather do something like `return not attr`. Actually, I'd remove the function completely and only use the `not`.

2019-08-07 11:00 UTC, KPilnacek commented on elisctl/connector.py
> +                raise click.ClickException("Queue ID(s) must be specified.")
```python
        if not queue_ids:
            queue_urls = [elis.get_queue()['url']]
        else:
            queue_urls = []
            for id_ in queue_ids:
                queue_dict = elis.get_queue(id_)
                if queue_dict:
                    queue_urls.append(queue_dict["url"])
```

2019-08-08 07:19 UTC, KPilnacek commented on elisctl/lib/api_client.py
> +                raise click.ClickException("Could not get queue ID.") from e
I don't think that `KeyError` can be raised in here. I guess, that [line 41 of `connector`](https://github.com/rossumai/elisctl/pull/75/files#diff-77d6c4254a50ad180ba59e1072305bddR41) module should have been wrapped in this `try ... except`.

If I'm mistaken, please provide a test to cover this part of code.

2019-08-08 07:19 UTC, KPilnacek commented on tests/test_connector.py
>          requests_mock.get(
this mock is not necessary anymore

2019-08-13 04:21 UTC, KPilnacek commented
LGTM 🙂 .

2019-08-13 04:22 UTC, KPilnacek approved these changes
LGTM, now, there are some merge conflicts. Please rebase and squash the branch before merging.

2019-08-13 07:47 UTC, merged