Add sample usage of elisctl library within Python code
rossumai/elisctl pull request #92
Opened 2019-12-13 10:21 UTC by evelyn9191

2019-12-16 18:36 UTC, pasky requested changes
Great idea. What do you think about my comments?

2019-12-16 18:36 UTC, pasky commented on README.md
> +                               f"&page_size=100&page=1")
Shouldn't we take this chance and use get_paginated() (or whatever it's called)? That is where the huge advantage of using the elisctl library actually comes in. We can then link this from our Python export example at dev hub, what do you think?

2019-12-16 18:36 UTC, pasky commented on README.md
> +export_format = "json"
Would the code even work with another export_format, given how the data is saved?

2019-12-16 18:36 UTC, pasky commented on README.md
> +
```suggestion

# This example downloads data for documents exported during the previous calendar day.
```

2019-12-18 14:53 UTC, evelyn9191 commented on README.md
> +export_format = "json"
Good catch, thanks!

2020-01-02 17:19 UTC, pasky approved these changes
Awesome

2020-01-02 17:19 UTC, merged