Require queue on user create
rossumai/elisctl pull request #96
Opened 2019-12-20 10:02 UTC by evelyn9191

2020-01-03 08:18 UTC, KPilnacek requested changes
LGTM, except a tiny nitpick.

2020-01-03 08:18 UTC, KPilnacek commented on elisctl/user.py
> +    help="Queue IDs, that the user will be associated with. Required field.",
No need to rephrase the help. This way the help looks like: `Queue IDs, that the user will be associated with. Required field.  [required]`.

btw just a nitpick: the part of english sentence starting with _that_ is not being started with comma (_which_ can be used in such a case). https://ell.stackexchange.com/questions/9154/use-of-commas-before-that

2020-01-03 16:07 UTC, evelyn9191 commented on elisctl/user.py
> +    help="Queue IDs, that the user will be associated with. Required field.",
Thanks for the advice!

2020-01-04 10:22 UTC, KPilnacek approved these changes

2020-01-06 09:46 UTC, merged

2020-02-18 13:49 UTC, evelyn9191 commented
Closes https://github.com/rossumai/elisctl/issues/81